@NeoIPC_Reporting_HostAddress = http://localhost:32770
@JsessionIdCookie = JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXXXX
@Accept_Language = en

### Get Reference Report as HTML
GET {{NeoIPC_Reporting_HostAddress}}/reference-report/
Accept: text/html
Accept-Language: {{Accept_Language}}
Cookie: {{JsessionIdCookie}}

### Get Reference Report as PDF
GET {{NeoIPC_Reporting_HostAddress}}/reference-report/
Accept: application/pdf
Accept-Language: {{Accept_Language}}
Cookie: {{JsessionIdCookie}}
